# INTRODUCTION TO NUMPY

Single dimensional Array

In [1]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

Multi-dimensional Array

In [2]:
import numpy as np
n2=np.array([[10,20,30,40],[50,60,70,80]])
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
print(type(n1))
print(type(n2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Intializing Numpy with zeros

In [6]:
import numpy as np
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
import numpy as np
n4=np.zeros((3,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Initializing Numpy array with the same Element

In [8]:
import numpy as np
n5=np.full((2,3),10)
n5

array([[10, 10, 10],
       [10, 10, 10]])

In [13]:
n6=np.full((2,4),9)
n6

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

Initializing numpy array within range

In [15]:
import numpy as np
n7=np.arange(10,50)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
n8=np.arange(10,60,2)
n8

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58])

Initializing numpy array with random numbers

In [20]:
import numpy as np
n9=np.random.randint(100,1000,10)
n9

array([345, 882, 834, 556, 403, 639, 273, 756, 484, 529])

 Checking the shape of numpy array 

In [21]:
import numpy as np
n10=np.array([[1,2,3],[4,5,6]])
n10.shape

(2, 3)

In [22]:
n10.shape=(3,2)
n10.shape

(3, 2)

In [23]:
n10


array([[1, 2],
       [3, 4],
       [5, 6]])

# Joining Numpy Arrays

S T A C K S()

In [26]:
import numpy as np
n11=np.array([10,20,30])
n12=np.array([40,50,60])

In [27]:
#vstack()
np.vstack((n11,n12))

array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
#hstack()
np.hstack((n11,n12))

array([10, 20, 30, 40, 50, 60])

In [29]:
#column_stack()
np.column_stack((n11,n12))

array([[10, 40],
       [20, 50],
       [30, 60]])